"""agregue tabla tareas

Revision ID: 65fb21df9a90
Revises: be7dbb7251b0
Create Date: 2023-03-10 22:59:01.466461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fb21df9a90'
down_revision = 'be7dbb7251b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'REALIZANDOSE', 'REALIZADA', 'CANCELADA', name='estadotareaenum'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    # ### end Alembic commands ###
